name-template: "app-$RESOLVED_VERSION"
tag-template: "app-$RESOLVED_VERSION"
tag-prefix: "app-"
exclude-labels:
  - helm-chart
categories:
  - title: Breaking Changes 💥
    labels:
      - breaking-change
  - title: New Features 🎉
    labels:
      - new-feature
  - title: Bug Fixes 🐛
    labels:
      - patch
  - title: Dependencies 📌
    labels:
      - dependencies
  - title: Other Changes 🛠
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "patch"
  default: patch
template: |

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION